Report common unrecoverable connection / authentication errors
elastic/sarama pull request #15
Opened 2022-03-04 18:59 UTC by faec

Many common connection errors that our users run into -- invalid server certificates, TLS version / cipher mismatches, and similar -- are not reported by the Sarama API, and appear only in Sarama's debug output, with log messages that often don't indicate the specific cause. Because Sarama treats these errors as recoverable, it retries many times, then returns the failure to Beats via the generic error "client has run out of brokers to talk to".

This PR adds four new internal error types to Sarama -- `ErrSASLHandshakeReadEOF`, `ErrSASLHandshakeSendEOF`, `ErrFetchMetadataEOF`, `ErrBadTLSHandshake` -- with descriptive error strings indicating how to troubleshoot the failure. It also treats these (as well as the preexisting `ErrUnsupportedSASLMechanism`) as unrecoverable errors, so they are reported directly back to Beats, where they are logged as an error. This should give much more useful / consistent log messages when there is an error connecting to a Kafka server.

## Testing details

These cases were analyzed and tested with a variant of the Beats Kafka container (in the beats repository under `testing/environments/docker`). In addition to the container's current plaintext port 9092 and SASL/SCRAM port 9093, it added a TLS port 9094 for checking TLS-only scenarios. Most tests were run with the Kafka output, with this baseline configuration:

```yml
output.kafka:
  hosts: ["127.0.0.1:9093"]

  topic: "filebeat-kafka-output-sasl-ssl"
  protocol: "https"
  sasl.mechanism: "SCRAM-SHA-512"

  ssl.certificate_authorities: ["/Users/fae/go/src/github.com/elastic/beats/testing/environments/docker/kafka/certs/ca-cert"]
  username: "beats"
  password: "KafkaTest"
```

Failures were then tested by varying the configurations, as follows:

- Bad password: change password to `"idk"`
- Bad server certificate: remove `ssl.certificate_authorities`
- Unsupported cipher: add `ssl.cipher_suites: [ECDHE-ECDSA-AES-128-CBC-SHA]`
- SASL client / plaintext broker: change `hosts` to `["127.0.0.1:9092"]`
- Unsupported TLS version: add `ssl.supported_protocols: [TLSv1.3]`
- Unsupported SASL mechanism: change `sasl.mechanism` to `"SCRAM-SHA-256"`
- TLS-only client, SASL broker: remove username/password and `sasl.mechanism`
- TLS-only client, unsupported TLS version: remove username/password and `sasl.mechanism`, add `ssl.supported_protocols: [TLSv1.3]`
- plaintext client, SASL broker: remove username/password and `sasl.mechanism`, change `protocol` to `"http"`

All these failure modes now give descriptive error logs when run against this PR.

2022-03-07 13:16 UTC, kvch requested changes
I would prefer if we checked errors using `errors.Is` function. Ref: https://go.dev/blog/go1.13-errors

2022-03-08 20:38 UTC, faec commented
> I would prefer if we checked errors using `errors.Is` function. Ref: https://go.dev/blog/go1.13-errors

That doesn't work for the TLS workaround check, but I switched all the other error checks to use it.

2022-03-09 20:25 UTC, faec commented
I'm unable to add some people on the team as reviewers... we might need to check the permissions on this repo to make sure they're up to date

2022-03-09 21:12 UTC, cmacknz approved these changes
Great error messages :thumbsup:. I have seen `"client has run out of brokers"` many times and it is not helpful at all. Thanks!

Do we have any changes here we want to commit upstream?

2022-03-10 12:36 UTC, kvch approved these changes

2022-03-10 19:33 UTC, faec commented
> Do we have any changes here we want to commit upstream?

Possibly, I will put a PR together. I expect they may want adjustments (e.g. this change is "safe" for us even though some recoverable errors may trigger it, because we have our own retry framework in the client, but some clients may behave differently), but we can at least report the specifics and see what they say.

2022-03-10 19:33 UTC, merged